arthur-trt/ft_transcendence

api/package-lock.json
api/package.json
api/src/auth/auth.controller.ts
api/src/auth/auth.module.ts

Bypass 42 OAuth for testing purpose

Adding auth_cheat

---

api/package-lock.json
api/package.json
api/src/auth/auth.controller.ts
api/src/auth/auth.module.ts
api/src/auth/auth.service.ts
api/src/auth/auth.strategy.ts
api/src/auth/guards/42-auth.guard.ts
api/src/auth/guards/jwt-auth.guard.ts
api/src/auth/jwt/jwt.constants.ts
api/src/auth/jwt/jwt.strategy.ts
api/src/main.ts
api/src/user/user.controller.ts

Authentification is now made by using cookie. For Postman (hello @Ccommiss ), you have in bottom right `Cookies`, you can add a cookie for localhost with this value :
```
Authentication=<token>; Path=/; Expires=Fri, 15 Jul 2022 10:55:52 GMT;
```

Add cookie generation and verification

---

api/src/dtos/uuid.dto.ts
api/src/user/user.controller.ts

Add me route

---

Caddyfile
api/entrypoint.sh
api/package-lock.json
api/package.json
api/src/app.module.ts
api/src/chat/chat.gateway.spec.ts
api/src/chat/chat.gateway.ts
api/src/chat/chat.module.ts
api/src/message/message.module.ts
api/src/user/user.entity.ts
docker-compose.yml

Little changes to caddy file to make it work with Hoppscotch.

28 creating gateway from main to be tested with hopscotch waiting for front possibility

---

api/src/auth/guards/ws-auth.guard.ts
api/src/chat/chat.gateway.ts

Check only our cookie

---

api/src/chat/chat.gateway.ts
api/src/dtos/sendPrivateMessageDto.dto.ts
api/src/message/message.controller.ts

Implementing users event for front

60 back sockets implementing more chatgateways

---

api/src/friendships/friendships.service.ts
api/src/websocket/wsserver.service.ts

Ability to get friend requests

get friend requests

---

api/src/auth/auth.service.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/Debug.tsx
frontend/src/components/Header.tsx
frontend/src/index.tsx

Add option to dynamically change cookie value for test with user. Don't work with current user in DB, have to log again. 
Cookie stored in localStorage (Inspect -> Application -> localStorage). 
Should be revert for prod use. (Sorry ANSSI)

126 debug option for websocket

---

README.md
api/src/main.ts
docker-compose.yml

Swagger is now on `<basepath>/docs/`

Change swagger path and handle by traefik

---

api/src/game/game.service.ts
api/src/websocket/wsserver.service.ts

removing friendships

---

api/src/auth/auth.service.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/TwoFactor.tsx
frontend/src/index.tsx

Some change : 
1/ Home page is now on `/`
2/ Login page is now on `/login`
Only login page is accessible without login. You can add protected page in your router by adding : 
```js
<RequireAuth><ProtecedPage /></RequireAuth>
```
in your `Router` in `index.tsx`

Add redirect to login if not logged in

---

api/src/channel/channel.entity.ts
api/src/channel/channel.service.ts
api/src/dtos/newChannel.dto.ts
api/src/dtos/sendChannelMessageDto.dto.ts
api/src/user/user.service.ts
api/src/websocket/exception.filter.ts
api/src/websocket/wsserver.gateway.ts
api/src/websocket/wsserver.module.ts
api/src/websocket/wsserver.service.ts

150 back implemeting private channels

---

api/src/auth/auth.controller.ts
api/src/auth/auth.service.ts
api/src/main.ts
docker-compose.yml

Add a new route for deactivate TwoFa. 
`POST /api/auth/2fa/deactivate`

Add route to deactivate twofa

---

api/src/user/user.service.ts

Fix provided by ccommiss without testing

---

api/src/channel/channel.service.ts
docker-compose.yml
frontend/src/components/Header.tsx
frontend/src/index.tsx

For this to work i had to remove the cookie and reload the page. So the `RequireAuth` in index can work.
No the best solution, because can't put the `HttpOnly` tag on the cookie, which add a security layer. But maybe we can just don't care ?

Almost working

---

api/src/auth/fortyTwo/fortyTwo.service.ts
api/src/websocket/exception.filter.ts
frontend/src/components/Channels-add.tsx
frontend/src/components/Header.tsx
frontend/src/components/TwoFactor.tsx
frontend/src/index.tsx

Reverts arthur-trt/ft_transcendence#312

Revert "Check logged user"

---

api/src/websocket/game.relayService.ts
api/src/websocket/wsserver.gateway.ts

Reverts arthur-trt/ft_transcendence#408

Revert "402 back achieve achievements"

---

api/src/game/game.interface.ts
api/src/game/game.service.ts
api/src/websocket/game.relayService.ts
api/src/websocket/wsserver.gateway.ts
frontend/src/components/Game.tsx

Reverts arthur-trt/ft_transcendence#433

Revert "430 back manage changement of tab"

---

env_conf.sh

Add timezone in env. You must add : 
```env
TZ="Europe/Paris"
```
Script have been updated

Change script to add timezone

---

api/src/channel/channel.service.ts

Reverts arthur-trt/ft_transcendence#634

Revert "631 gnagnagna on enleve pas le owner"

---

api/src/user/user.service.ts

Reverts arthur-trt/ft_transcendence#632

Revert "pouet"
